### ISSUE TITLE
Images pastes without an extension are not displayed correctly in Firefox

### ISSUE THREAD

**Issue by HalosGhost** [ptpb/pb#128]
An image paste loaded in Firefox without an extension added to the end of the id will not correctly display (instead, the binary data will be output).

**Comment by buhman** [comment]
Needs testcase.

**Comment by HalosGhost** [comment]
If, for example, you navigate to [this paste](https://ptpb.pw/R3BT) in Firefox, you will see the following:

![binary junk](https://ptpb.pw/8UWr.png)

If, instead, you navigate to the [same paste with a file extension specified](https://ptpb.pw/R3BT.jpg) (note that you can give it an incorrect file extension), you will find this:

![the image](https://ptpb.pw/R3BT.jpg)

**Comment by buhman** [comment]
Ahh. Not a bug. It's intended that you override the default text/plain with your extension, because doing it this way is fast and simple to implement.

Otherwise, it's possible to libmagic the body on every GET (or calculate this once and store the result in the db).

So uh.. how do you want this to work exactly?

If you `-F @c=foo.jpg` right now, you get `<shortid>.jpg` back. Would you rather I also set the 'default' mimetype for `<shortid>` to jpg for that paste as well?

**Comment by HalosGhost** [comment]
I think that using libmagic on every ``GET`` seems like a sadtime; but using it once and storing it (probably on upload so that it handles paste updating fine) seems like it'd be a good idea (since it would gracefully handle stdin cases).

Does that make sense to you?

**Comment by buhman** [comment]
Yep.

**Comment by HalosGhost** [comment]
Great! I look forward to the implementation!

**Comment by buhman** [comment]
3ca079ad0ed0cbdbe715eab44f462648e0dc61b9

**Comment by buhman** [comment]
> note that you can give it an incorrect file extension

Not a bug.
