### ISSUE TITLE
No picture of baby skunk

### ISSUE THREAD

**Issue by xelra** [ptpb/pb#133]
Hi, I've read through the help page and I noticed that there's no picture of a baby skunk at [https://ptpb.pw/ullp](https://ptpb.pw/ullp).

![untitled](https://cloud.githubusercontent.com/assets/908568/10690345/5a61388e-7981-11e5-94cf-0b71e3de694d.png)

I was very disappointed when I opened that link. :)

**Comment by HalosGhost** [comment]
:+1:

**Comment by buhman** [comment]
So `ullp` is an ancient `[pid_id](https://github.com/ptpb/pb/blob/pre-url/util.py#L48)`, which instead of corresponding to some digest, is actually related to a row with int id == `-4564631`.

There was a reason negative ids were used, but I can't remember. Also no idea where I got the picture from.

**Comment by buhman** [comment]
`ullp` corresponds to a sha1 digest that ends with `ba5969`. Someone should start a project to hash all the baby skunk pictures to find out which one corresponds to `ullp`.

**Comment by buhman** [comment]
> I was doing DELETE calls on documentation pastes

I mean, it's even in the docs, I just realized.

```
$ curl -X DELETE https://ptpb.pw/17c5829d-81a0-4eb6-8681-ba72f83ffbf3
https://ptpb.pw/ullp deleted.
```

Why are we even surprised?
