### ISSUE TITLE
URL shortening doesn't work when passing the URL only flag: /?u=1

### ISSUE THREAD

**Issue by cwre** [ptpb/pb#186]
<img width="591" alt="screen shot 2017-03-21 at 3 25 29 pm" src="https://cloud.githubusercontent.com/assets/6749810/24166719/a2d1f86a-0e4a-11e7-9428-52bd010c3da6.png">

```
# ishmael @ aegislash in ~ [15:22:58]
$ curl -F c=@- https://ptpb.pw/\?u\=1 <<< https://imgur.com/gallery/dT95uNi
https://ptpb.pw/wjs_

# ishmael @ aegislash in ~ [15:24:53]
$ curl -F c=@- https://ptpb.pw/u <<< https://imgur.com/gallery/dT95uNi
date: 2017-03-21T19:24:58.330693+00:00
digest: c0a697c0eee44a809469b0af5b46b5d3c98d3c6f
long: AMCml8Du5EqAlGmwr1tGtdPJjTxv
redirect: 1
short: jTxv
size: 33
status: created
url: https://ptpb.pw/jTxv
```

Different flag provides two different pastes, one gives me the actual redirect, the other gives me the url in a paste.

**Comment by cwre** [comment]
Also seems like the detection for strictly shortening the URL isn't working. I can't shorten this url either, it just pastes the url: https://ptpb.pw/wW4O

**Comment by buhman** [comment]
I'm very aware shorturl-related things could probably be improved.

> I can't shorten this url either

The current behavior is: if it already exists as a paste, you can't (re)create it as a shorturl.

> ?u=1

I added this because people were complaining about how the default response behavior was "too complicated" or "too verbose", etc… This is only a display-related thing--instead of yaml, you get just a string which is the paste/shorturl. It is also completely unrelated to the `/u` route, despite having the same letter.

> URL shortening doesn't work when passing the URL only flag: /?u=1

That's because that's not the shorturl route. You want `/u` instead.

---

Other than the API being bad/inconsistent, is there an actual bug here?

**Comment by buhman** [comment]
I also realize maybe you're actually asking for `/u` to support `?u=1`, which I imagine it probably doesn't(?). I would definitely agree with a request to refactor that view completely.

**Comment by cwre** [comment]
So I think maybe I was being an idiot. I attempted to shorten this url just now and it seems to work: https://ptpb.pw/YhtO

I am using Hammerspoon on my Mac to create a pbpst like functionality on OSX. I've stopped trying to use the URL only output and instead am using regex to pull the url: via the tag in front of it.

It seems to be working, so I'll close this.

Sorry for the confusion!

**Comment by buhman** [comment]
No problem!
