### ISSUE TITLE
AUR updates

### ISSUE THREAD

**Issue by Nic321** [ptpb/pb#191]
Really appreciate your quick response to this issue:

https://github.com/ptpb/pb/issues/189

Will there be an update coming to AUR soon? Just noticed you're the maintainer :) but it hasn't been updated since 2016-01-23 21:51 :(

Thanks again. Loving pb.

**Comment by buhman** [comment]
I'll check it out.

**Comment by buhman** [comment]
The aur comments are correct, and the problem is I never tried this in a clean chroot. Luckily, grunt-run-grunt masks the real error from gm:

```
>> Command failed: gm convert: Unable to load module ("/usr/lib/GraphicsMagick-1.3.25/modules-Q16/coders/svg.la: file not found").
```

This is actually an incorrect error message, because that file definitely exists. I repo'ed the `gm convert`, then found during strace the error message is written after opening `/usr/lib/GraphicsMagick-1.3.25/modules-Q16/coders/svg.so`. 

``` shell-session
$ ldd /usr/lib/GraphicsMagick-1.3.25/modules-Q16/coders/svg.so
	libxml2.so.2 => not found
```

This is clearly a packaging error by the archlinux gm package maintainer. However, it's easy enough to hack around this in pb-git's makedepends.

**Comment by buhman** [comment]
Also someone conveniently removed `python-flask-git`, even though pb no longer actually needs that (0.11 is released and packaged).

**Comment by buhman** [comment]
So, I fixed a few longstanding issues:

 * asciinema-player is no longer randomly part of pb's build process
   * instead of being stuffed in the appropriately-named `hack` directly, it is now built in pbs: https://github.com/ptpb/pbs/commit/15ba7a332281533cc57dfeb219d15c605c20276c
 * this allows me to remove the package.json/gruntfile cruft from pb completely
 * I then updated how pb/flask finds static files in https://github.com/ptpb/pb/commit/dc04f7f6bbe94a9ebc944ea3d3d1a049bfb2350d

This means pb and pbs can now be built separately, so the aur packaging now reflects this:

 * [aur/pb-git](https://aur.archlinux.org/packages/pb-git)@r357.dc04f7f
 * [aur/pbs-git](https://aur.archlinux.org/packages/pbs-git)@r13.15ba7a3

and, pbs-git is an optdepends, so you can use the ptpb.pw/other cdn prefix if desired instead.

:+1: :100: :shipit:

**Comment by buhman** [comment]
Let me know if you have any other problems not related to building.
